const itemValues = [
    "Passport",
    "Driver's License",
    "Travel Tickets",
    "Hotel Reservations",
    "Travel Itinerary",
    "Credit Cards",
    "Cash",
    "Travel Insurance",
    "Medications",
    "Prescription Glasses/Contacts",
    "Sunscreen",
    "Insect Repellent",
    "First Aid Kit",
    "Toothbrush",
    "Toothpaste",
    "Dental Floss",
    "Shampoo",
    "Conditioner",
    "Body Wash",
    "Face Wash",
    "Moisturizer",
    "Razor",
    "Shaving Cream",
    "Hairbrush/Comb",
    "Hair Styling Products",
    "Deodorant",
    "Makeup",
    "Makeup Remover",
    "Tampons/Pads",
    "Hand Sanitizer",
    "Tissues",
    "Wet Wipes",
    "Hand Cream",
    "Lip Balm",
    "Sun Hat",
    "Sunglasses",
    "Beach Towel",
    "Swimsuit",
    "Flip Flops",
    "Sandals",
    "Hiking Shoes",
    "Sneakers",
    "Dress Shoes",
    "Casual Clothing",
    "Formal Clothing",
    "Jacket/Sweater",
    "Raincoat/Umbrella",
    "Pajamas",
    "Underwear",
    "Socks",
    "Belt",
    "Hats/Caps",
    "Gloves",
    "Scarf",
    "Watch/Jewelry",
    "Backpack",
    "Day Bag",
    "Beach Bag",
    "Reusable Water Bottle",
    "Snacks",
    "Travel Pillow",
    "Earplugs",
    "Sleep Mask",
    "Books/Kindle",
    "Journal",
    "Pen/Pencil",
    "Camera",
    "Chargers (Phone, Camera, etc.)",
    "Power Bank",
    "Adapters/Converters",
    "Portable Speaker",
    "Travel Locks",
    "Luggage Tags",
    "Laundry Bag",
    "Swiss Army Knife/Multi-tool",
    "Travel Sewing Kit",
    "Duct Tape",
    "Safety Pins",
    "Travel Guides/Maps",
    "Language Phrasebook",
    "Travel Apps (e.g., Maps, Translation)",
    "Snorkel Gear",
    "Scuba Diving Equipment",
    "Surfboard",
    "Skis/Snowboard",
    "Golf Clubs",
    "Tennis Racket",
    "Running Shoes",
    "Yoga Mat",
    "Fishing Gear",
    "Camping Equipment",
    "Binoculars",
    "Portable Grill",
    "Cooler",
    "Picnic Blanket",
    "Bluetooth Speaker",
    "Portable Hammock",
    "Board Games",
    "Playing Cards",
    "Sketchbook/Art Supplies",
    "Musical Instrument",
    "Travel Hammock",
    "Travel Yoga Mat",
    "Reusable Straws",
    "Reusable Shopping Bags",
    "Tote Bag",
    "Handheld Fan",
    "Travel Iron",
    "Lint Roller",
    "Travel Steamer",
    "Collapsible Water Bottle",
    "Compact Umbrella",
    "Headphones/Earbuds",
    "Travel Toothbrush Holder",
    "Travel Shaving Kit",
    "Travel Hair Dryer",
    "Travel Laundry Detergent",
    "Travel Size Toiletries",
    "Compact Travel Mirror",
    "Travel Organizer Cubes",
    "Compression Socks",
    "Motion Sickness Medication",
    "Travel Neck Pillow",
    "Travel Blanket",
    "Travel Eye Mask",
    "Travel Earplugs",
    "Travel Wallet",
    "Portable Luggage Scale",
    "Foldable Travel Backpack",
    "Portable WiFi Hotspot",
    "Travel Insurance Documents",
    "Emergency Contact Information",
    "Local Currency",
    "International Driving Permit",
    "Travel Adapter Plug",
    "Photocopies of Important Documents",
    "Travel Visa/Entry Documents",
    "Travel Rewards Cards",
    "Emergency Cash Stash",
    "Portable Travel Fan",
    "Reusable Cutlery Set",
    "Travel Hand Sanitizer",
    "Travel Tissues",
    "Compact Travel Towel",
    "Travel Pillowcase",
    "Travel Hairbrush",
    "Travel Makeup Bag",
    "Travel Jewelry Organizer",
    "Travel Laundry Bag",
    "Travel Shoe Bags",
    "Travel Compression Bags",
    "Travel Packing Cubes",
    "Travel Toiletry Bag",
    "Travel Shoe Organizer",
    "Travel Garment Folder",
    "Travel RFID Wallet",
    "Travel Passport Holder",
    "Travel Document Organizer",
    "Travel Camera Bag",
    "Travel Laptop Bag",
    "Travel Tablet Sleeve",
    "Travel External Hard Drive",
    "Travel USB Flash Drive",
    "Travel Laptop Lock",
    "Travel Laptop Stand",
    "Travel Laptop Cooling Pad",
    "Travel Laptop Charger",
    "Travel Laptop Case",
    "Travel Laptop Sleeve",
    "Travel Laptop Skin",
    "Travel Laptop Decal",
    "Travel Laptop Backpack",
    "Travel Laptop Sleeve with Pocket",
    "Travel Laptop Sleeve with Handle",
    "Travel Laptop Sleeve with Strap",
    "Travel Laptop Sleeve with Zipper",
    "Travel Laptop Sleeve with Shoulder Strap",
];

module.exports = itemValues;